"""comentario

Revision ID: 477673047a69
Revises: 
Create Date: 2020-11-27 00:30:41.674092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477673047a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_categoria'), 'categoria', ['categoria'], unique=True)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=64), nullable=True),
    sa.Column('apellidos', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('politica', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_apellidos'), 'persona', ['apellidos'], unique=True)
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=True)
    op.create_index(op.f('ix_persona_nombres'), 'persona', ['nombres'], unique=True)
    op.create_index(op.f('ix_persona_username'), 'persona', ['username'], unique=True)
    op.create_table('tipo_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiporol', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_rol_tiporol'), 'tipo_rol', ['tiporol'], unique=True)
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre_curso', sa.String(length=120), nullable=True),
    sa.Column('descripcion_curso', sa.String(length=120), nullable=True),
    sa.Column('frase_curso', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_descripcion_curso'), 'curso', ['descripcion_curso'], unique=True)
    op.create_index(op.f('ix_curso_frase_curso'), 'curso', ['frase_curso'], unique=True)
    op.create_index(op.f('ix_curso_nombre_curso'), 'curso', ['nombre_curso'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('tipo_rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_rol_id'], ['tipo_rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oferta_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('fechainicio', sa.String(length=64), nullable=True),
    sa.Column('fechafin', sa.String(length=64), nullable=True),
    sa.Column('tema_periodo', sa.String(length=64), nullable=True),
    sa.Column('contenido_tema', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oferta_curso_contenido_tema'), 'oferta_curso', ['contenido_tema'], unique=True)
    op.create_index(op.f('ix_oferta_curso_fechafin'), 'oferta_curso', ['fechafin'], unique=True)
    op.create_index(op.f('ix_oferta_curso_fechainicio'), 'oferta_curso', ['fechainicio'], unique=True)
    op.create_index(op.f('ix_oferta_curso_tema_periodo'), 'oferta_curso', ['tema_periodo'], unique=True)
    op.create_table('plan_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('unidad_curso', sa.String(length=64), nullable=True),
    sa.Column('periodo_unidad', sa.String(length=64), nullable=True),
    sa.Column('tema_periodo', sa.String(length=64), nullable=True),
    sa.Column('contenido_tema', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_curso_contenido_tema'), 'plan_curso', ['contenido_tema'], unique=True)
    op.create_index(op.f('ix_plan_curso_periodo_unidad'), 'plan_curso', ['periodo_unidad'], unique=True)
    op.create_index(op.f('ix_plan_curso_tema_periodo'), 'plan_curso', ['tema_periodo'], unique=True)
    op.create_index(op.f('ix_plan_curso_unidad_curso'), 'plan_curso', ['unidad_curso'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_curso_unidad_curso'), table_name='plan_curso')
    op.drop_index(op.f('ix_plan_curso_tema_periodo'), table_name='plan_curso')
    op.drop_index(op.f('ix_plan_curso_periodo_unidad'), table_name='plan_curso')
    op.drop_index(op.f('ix_plan_curso_contenido_tema'), table_name='plan_curso')
    op.drop_table('plan_curso')
    op.drop_index(op.f('ix_oferta_curso_tema_periodo'), table_name='oferta_curso')
    op.drop_index(op.f('ix_oferta_curso_fechainicio'), table_name='oferta_curso')
    op.drop_index(op.f('ix_oferta_curso_fechafin'), table_name='oferta_curso')
    op.drop_index(op.f('ix_oferta_curso_contenido_tema'), table_name='oferta_curso')
    op.drop_table('oferta_curso')
    op.drop_table('user')
    op.drop_index(op.f('ix_curso_nombre_curso'), table_name='curso')
    op.drop_index(op.f('ix_curso_frase_curso'), table_name='curso')
    op.drop_index(op.f('ix_curso_descripcion_curso'), table_name='curso')
    op.drop_table('curso')
    op.drop_index(op.f('ix_tipo_rol_tiporol'), table_name='tipo_rol')
    op.drop_table('tipo_rol')
    op.drop_index(op.f('ix_persona_username'), table_name='persona')
    op.drop_index(op.f('ix_persona_nombres'), table_name='persona')
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.drop_index(op.f('ix_persona_apellidos'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_categoria_categoria'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
